version: '3'

services:
  qbot:
    container_name: qbot
    volumes:
      - .:/qbot
    env_file:
      - .env
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - 4001:4001
    networks:
      - qbot

  gocq:
    container_name: gocq
    volumes:
      - .:/qbot
    build: .
    environment:
      TZ: Asia/Shanghai
    
    depends_on:
      - qbot
    command: ["/qbot/go-cqhttp", "-faststart"]
    networks:
      - qbot
      
networks:
  qbot:
    name: qbot
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
